create get user api
BlackBoxBanner/cpe-space-backend pull request #15
Opened 2024-04-07 16:13 UTC by redbiiddsun

2024-04-07 16:18 UTC, redbiiddsun commented
@BlackBoxBanner Where r u!!!!!

2024-04-07 16:23 UTC, BlackBoxBanner requested changes

2024-04-07 16:23 UTC, BlackBoxBanner commented on src/controllers/users.controller.ts
> +    UserExcludePassword | null
remove null pls

2024-04-07 16:23 UTC, redbiiddsun commented on src/controllers/users.controller.ts
> +    UserExcludePassword | null
no I wont do it

2024-04-07 16:23 UTC, redbiiddsun commented on src/controllers/users.controller.ts
> +    UserExcludePassword | null
do it by yourself

2024-04-08 11:18 UTC, BlackBoxBanner approved these changes

2024-04-08 11:19 UTC, merged